spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/b2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1773192042@qq.com
    password: oalpbrzegsfoddbd # 授权码
  redis:
    host: 127.0.0.1
#    password: root
server:
  port: 8001
logging:
  level:
    com.qf: debug
blog:
  host: http://localhost:${server.port}/